name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20" # Node.js のバージョンを20に更新

      - name: Create public directory
        run: mkdir -p public # publicディレクトリがなければ作成

      - name: Create env file
        run: |
          echo "const CONFIG = { API_KEY: '${{ secrets.API_KEY }}' };" > public/config.js
        env:
          GITHUB_TOKEN: ${{ secrets.LEARNING_EN_TOKEN }}
          API_KEY: ${{ secrets.API_KEY }} # GitHub SecretsからAPIキーを取得

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.LEARNING_EN_TOKEN }}
          publish_dir: ./public
