name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy to GitHub Pages
      env:
        API_KEY: ${{ secrets.API_KEY }}
        AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
      run: |
        # HTMLファイルに環境変数を注入
        sed -i "s/API_KEY: ''/API_KEY: '${{ env.API_KEY }}'/g" index.html
        
        # GitHub Pagesにデプロイ
        git config --global user.name 'MariNakamura'
        git config --global user.email 'nakamura@incubatefund.com'
        git add index.html
        git commit -m "Inject env vars"
        git push












